### ISSUE TITLE
empty record is created if the iterator item is a folder

### ISSUE THREAD

**Issue by WeirdMagician** [WeirdMagician/conduit-connector-google-cloudstorage#12]
### Bug description

During the snapshot or cdc iterator and empty record is created when the read item is only a folder.
Instead it should be avoided.

### Steps to reproduce

Create the GCP bucket with folders in it and test the gcp source connector with the file destination to view the empty records

### Version

v0.1.0

**Comment by hariso** [comment]
@WeirdMagician I'd like to go one step back and think about what we want to achieve, not necessarily how. The "what" is pulling folders, the information you provided (which is super useful!) is the "how". 

IIUC, folders are not something which exists in GCS as a first class citizen: you can't list them, get them by ID, update, delete etc. From that point of view, I don't think we should pull them.

@maha-hajja @uchennakevinm1 what are your thoughts here?

**Comment by maha-hajja** [comment]
@hariso umm makes sense.. we could still pull them but then check the type and if it's a folder then ignore it.. but would anyone using the connector always expect to get their folders for some specific reason? we'd be ruining that if we ignore them

**Comment by WeirdMagician** [comment]
@hariso as discussed everything in the bucket is a object there is no differentiation like folders or files but only for the visual representation the objects are shown as folders(object name ending with slash) and files through the GCS console. But in the back-end there is no metadata to identify the differentiation.

So we are closing the issue as it is a default behavior of GCS.
